import { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { supabase } from '@/integrations/supabase/client';

export type Language = 'en' | 'es' | 'fr' | 'de' | 'zh' | 'ar' | 'pt' | 'ru' | 'ja' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.profile': 'Profile',
    'nav.notifications': 'Notifications',
    
    // Header
    'header.appTitle': 'CarCare',
    'header.appSubtitle': 'Your digital co-pilot',
    'header.signOutSuccess': 'Signed out successfully',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    
    // Service Centers
    'services.title': 'Service Centers',
    'services.findNearby': 'Find Nearby Places',
    'services.enableLocation': 'Enable Location',
    'services.searchByCategory': 'Search by Category',
    'services.serviceCenters': 'Service Centers',
    'services.carWash': 'Car Wash',
    'services.gasStations': 'Gas Stations',
    'services.getDirections': 'Get Directions',
    'services.routeTo': 'Route to',
    'services.foundPlaces': 'Found Places',
    'services.clickCategory': 'Click a category to search',
    'services.searching': 'Searching...',
    'services.kmAway': 'km away',
    
    // Profile
    'profile.title': 'Profile',
    'profile.language': 'Language',
    'profile.selectLanguage': 'Select Language',
    'profile.carInfo': 'Car Information',
    'profile.personalInfo': 'Personal Information',
    'profile.fullName': 'Full Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone Number',
    'profile.carMake': 'Car Make',
    'profile.carModel': 'Car Model',
    'profile.carYear': 'Car Year',
    'profile.carPlate': 'License Plate',
    'profile.subscription': 'Subscription',
    'profile.logout': 'Logout',
    
    // Dashboard
    'dashboard.maintenance': 'Maintenance Status',
    'dashboard.oil': 'Oil',
    'dashboard.gas': 'Gas',
    'dashboard.parking': 'Parking Spot',
    'dashboard.noParking': 'No parking spot saved',
    'dashboard.saveSpot': 'Save Current Spot',
    'dashboard.spotSaved': 'Parking spot saved!',
    'dashboard.locationMarked': 'Location marked at your current position',
    'dashboard.openingNav': 'Opening navigation...',
    'dashboard.documents': 'Document Expiry',
    'dashboard.nextExpire': 'Next to expire',
    'dashboard.daysLeft': 'days left',
    'dashboard.insurance': 'Insurance',
    'dashboard.registration': 'Registration',
    'dashboard.inspection': 'Inspection',
    'dashboard.finance': 'Financial Overview',
    'dashboard.thisMonth': 'this month',
    'dashboard.lessThanLast': 'less than last month',
    'dashboard.maintenance2': 'Maintenance',
    'dashboard.logExpense': 'Log Expense',
    'dashboard.expenseSoon': 'Expense logging feature coming soon!',
    
    // Mileage Tracker
    'mileage.title': 'Mileage Tracker',
    'mileage.currentTrip': 'Current Trip',
    'mileage.readyTrack': 'Ready to Track',
    'mileage.startTracking': 'Start Tracking',
    'mileage.stopSave': 'Stop & Save',
    'mileage.trackingStarted': 'Tracking Started',
    'mileage.recording': 'Recording your mileage...',
    'mileage.tripSaved': 'Trip Saved',
    'mileage.distance': 'Distance',
    'mileage.tripHistory': 'Trip History',
    'mileage.clear': 'Clear',
    'mileage.historyCleared': 'History Cleared',
    'mileage.dataReset': 'All trip data has been reset',
    'mileage.noTrips': 'No trips recorded yet',
    'mileage.totalMileage': 'Total Mileage',
    'mileage.trip': 'Trip',
    'mileage.howWorks': 'How it works',
    'mileage.usesGPS': 'The mileage tracker uses your device\'s GPS to automatically calculate distance traveled.',
    'mileage.startBefore': 'Start tracking before your trip and stop when you\'re done. All trips are saved to your history.',
    'mileage.requiresLocation': 'Note: Requires location permissions and works best with high GPS accuracy.',
    'mileage.lat': 'Lat',
    'mileage.lng': 'Lng',
    'mileage.accuracy': 'Accuracy',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.push': 'Push Notifications',
    'notifications.enabled': 'Enabled',
    'notifications.disabled': 'Disabled',
    'notifications.enableReceive': 'Enable notifications to receive alerts about:',
    'notifications.maintenanceReminders': 'Upcoming maintenance reminders',
    'notifications.expirationWarnings': 'Document expiration warnings',
    'notifications.appointments': 'Service appointment confirmations',
    'notifications.updates': 'Important vehicle updates',
    'notifications.deviceToken': 'Device Token',
    'notifications.howWorks': 'How it works',
    'notifications.whenEnabled': 'When you enable push notifications, CarCare can send you timely alerts even when the app is closed.',
    'notifications.requiresNative': 'Note: Push notifications require the native mobile app (iOS or Android). They won\'t work in the web browser.',
    
    // Subscription
    'subscription.title': 'Subscription Plans',
    'subscription.subtitle': 'Choose the plan that works for you',
    'subscription.currentPlan': 'Current Plan',
    'subscription.renewsOn': 'Your premium access renews on',
    'subscription.manageSubscription': 'Manage Subscription',
    'subscription.statusRefreshed': 'Subscription status refreshed',
    'subscription.checkoutError': 'Failed to create checkout session',
    'subscription.portalError': 'Failed to open customer portal',
    'subscription.generalError': 'Something went wrong',
    'subscription.loading': 'Loading...',
    'subscription.free': 'Free',
    'subscription.premium': 'Premium',
    'subscription.active': 'Active',
    'subscription.perMonth': '/month',
    'subscription.upgradeToPremium': 'Upgrade to Premium',
    'subscription.freeFeature1': 'Basic maintenance tracking',
    'subscription.freeFeature2': 'Save 1 parking spot',
    'subscription.freeFeature3': 'View upcoming document expiry',
    'subscription.freeFeature4': 'Basic expense tracking',
    'subscription.premiumFeature1': 'Unlimited maintenance tracking',
    'subscription.premiumFeature2': 'Unlimited parking spots with map',
    'subscription.premiumFeature3': 'Document expiry alerts',
    'subscription.premiumFeature4': 'Advanced financial insights',
    'subscription.premiumFeature5': 'Priority support',
    'subscription.premiumFeature6': 'Export reports',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.services': 'Servicios',
    'nav.profile': 'Perfil',
    'nav.notifications': 'Notificaciones',
    
    'header.appTitle': 'CarCare',
    'header.appSubtitle': 'Tu copiloto digital',
    'header.signOutSuccess': 'Sesión cerrada exitosamente',
    
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.back': 'Atrás',
    
    'services.title': 'Centros de Servicio',
    'services.findNearby': 'Encontrar Lugares Cercanos',
    'services.enableLocation': 'Activar Ubicación',
    'services.searchByCategory': 'Buscar por Categoría',
    'services.serviceCenters': 'Centros de Servicio',
    'services.carWash': 'Lavado de Autos',
    'services.gasStations': 'Gasolineras',
    'services.getDirections': 'Obtener Direcciones',
    'services.routeTo': 'Ruta a',
    'services.foundPlaces': 'Lugares Encontrados',
    'services.clickCategory': 'Haz clic en una categoría para buscar',
    'services.searching': 'Buscando...',
    'services.kmAway': 'km de distancia',
    
    'profile.title': 'Perfil',
    'profile.language': 'Idioma',
    'profile.selectLanguage': 'Seleccionar Idioma',
    'profile.carInfo': 'Información del Automóvil',
    'profile.personalInfo': 'Información Personal',
    'profile.fullName': 'Nombre Completo',
    'profile.email': 'Correo Electrónico',
    'profile.phone': 'Número de Teléfono',
    'profile.carMake': 'Marca del Auto',
    'profile.carModel': 'Modelo del Auto',
    'profile.carYear': 'Año del Auto',
    'profile.carPlate': 'Placa',
    'profile.subscription': 'Suscripción',
    'profile.logout': 'Cerrar Sesión',
    
    'dashboard.maintenance': 'Estado de Mantenimiento',
    'dashboard.oil': 'Aceite',
    'dashboard.gas': 'Gasolina',
    'dashboard.parking': 'Lugar de Estacionamiento',
    'dashboard.noParking': 'No hay lugar guardado',
    'dashboard.saveSpot': 'Guardar Lugar Actual',
    'dashboard.spotSaved': '¡Lugar guardado!',
    'dashboard.locationMarked': 'Ubicación marcada en tu posición actual',
    'dashboard.openingNav': 'Abriendo navegación...',
    'dashboard.documents': 'Vencimiento de Documentos',
    'dashboard.nextExpire': 'Próximo a vencer',
    'dashboard.daysLeft': 'días restantes',
    'dashboard.insurance': 'Seguro',
    'dashboard.registration': 'Registro',
    'dashboard.inspection': 'Inspección',
    'dashboard.finance': 'Resumen Financiero',
    'dashboard.thisMonth': 'este mes',
    'dashboard.lessThanLast': 'menos que el mes pasado',
    'dashboard.maintenance2': 'Mantenimiento',
    'dashboard.logExpense': 'Registrar Gasto',
    'dashboard.expenseSoon': '¡Función de registro de gastos próximamente!',
    
    'mileage.title': 'Rastreador de Kilometraje',
    'mileage.currentTrip': 'Viaje Actual',
    'mileage.readyTrack': 'Listo para Rastrear',
    'mileage.startTracking': 'Iniciar Rastreo',
    'mileage.stopSave': 'Detener y Guardar',
    'mileage.trackingStarted': 'Rastreo Iniciado',
    'mileage.recording': 'Registrando tu kilometraje...',
    'mileage.tripSaved': 'Viaje Guardado',
    'mileage.distance': 'Distancia',
    'mileage.tripHistory': 'Historial de Viajes',
    'mileage.clear': 'Limpiar',
    'mileage.historyCleared': 'Historial Limpiado',
    'mileage.dataReset': 'Todos los datos del viaje han sido reiniciados',
    'mileage.noTrips': 'No hay viajes registrados aún',
    'mileage.totalMileage': 'Kilometraje Total',
    'mileage.trip': 'Viaje',
    'mileage.howWorks': 'Cómo funciona',
    'mileage.usesGPS': 'El rastreador de kilometraje usa el GPS de tu dispositivo para calcular automáticamente la distancia recorrida.',
    'mileage.startBefore': 'Inicia el rastreo antes de tu viaje y detén cuando termines. Todos los viajes se guardan en tu historial.',
    'mileage.requiresLocation': 'Nota: Requiere permisos de ubicación y funciona mejor con alta precisión de GPS.',
    'mileage.lat': 'Lat',
    'mileage.lng': 'Lng',
    'mileage.accuracy': 'Precisión',
    
    'notifications.title': 'Notificaciones',
    'notifications.push': 'Notificaciones Push',
    'notifications.enabled': 'Habilitado',
    'notifications.disabled': 'Deshabilitado',
    'notifications.enableReceive': 'Habilita las notificaciones para recibir alertas sobre:',
    'notifications.maintenanceReminders': 'Recordatorios de mantenimiento próximo',
    'notifications.expirationWarnings': 'Advertencias de vencimiento de documentos',
    'notifications.appointments': 'Confirmaciones de citas de servicio',
    'notifications.updates': 'Actualizaciones importantes del vehículo',
    'notifications.deviceToken': 'Token del Dispositivo',
    'notifications.howWorks': 'Cómo funciona',
    'notifications.whenEnabled': 'Cuando habilitas las notificaciones push, CarCare puede enviarte alertas oportunas incluso cuando la aplicación está cerrada.',
    'notifications.requiresNative': 'Nota: Las notificaciones push requieren la aplicación móvil nativa (iOS o Android). No funcionan en el navegador web.',
    
    'subscription.title': 'Planes de Suscripción',
    'subscription.subtitle': 'Elige el plan que funcione para ti',
    'subscription.currentPlan': 'Plan Actual',
    'subscription.renewsOn': 'Tu acceso premium se renueva el',
    'subscription.manageSubscription': 'Gestionar Suscripción',
    'subscription.statusRefreshed': 'Estado de suscripción actualizado',
    'subscription.checkoutError': 'Error al crear sesión de pago',
    'subscription.portalError': 'Error al abrir portal del cliente',
    'subscription.generalError': 'Algo salió mal',
    'subscription.loading': 'Cargando...',
    'subscription.free': 'Gratis',
    'subscription.premium': 'Premium',
    'subscription.active': 'Activo',
    'subscription.perMonth': '/mes',
    'subscription.upgradeToPremium': 'Actualizar a Premium',
    'subscription.freeFeature1': 'Seguimiento básico de mantenimiento',
    'subscription.freeFeature2': 'Guardar 1 lugar de estacionamiento',
    'subscription.freeFeature3': 'Ver próximo vencimiento de documentos',
    'subscription.freeFeature4': 'Seguimiento básico de gastos',
    'subscription.premiumFeature1': 'Seguimiento ilimitado de mantenimiento',
    'subscription.premiumFeature2': 'Lugares de estacionamiento ilimitados con mapa',
    'subscription.premiumFeature3': 'Alertas de vencimiento de documentos',
    'subscription.premiumFeature4': 'Información financiera avanzada',
    'subscription.premiumFeature5': 'Soporte prioritario',
    'subscription.premiumFeature6': 'Exportar reportes',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.services': 'Services',
    'nav.profile': 'Profil',
    'nav.notifications': 'Notifications',
    
    'header.appTitle': 'CarCare',
    'header.appSubtitle': 'Votre copilote numérique',
    'header.signOutSuccess': 'Déconnexion réussie',
    
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.back': 'Retour',
    
    'services.title': 'Centres de Service',
    'services.findNearby': 'Trouver des Lieux à Proximité',
    'services.enableLocation': 'Activer la Localisation',
    'services.searchByCategory': 'Rechercher par Catégorie',
    'services.serviceCenters': 'Centres de Service',
    'services.carWash': 'Lavage Auto',
    'services.gasStations': 'Stations-Service',
    'services.getDirections': 'Obtenir l\'Itinéraire',
    'services.routeTo': 'Route vers',
    'services.foundPlaces': 'Lieux Trouvés',
    'services.clickCategory': 'Cliquez sur une catégorie pour rechercher',
    'services.searching': 'Recherche...',
    'services.kmAway': 'km',
    
    'profile.title': 'Profil',
    'profile.language': 'Langue',
    'profile.selectLanguage': 'Sélectionner la Langue',
    'profile.carInfo': 'Informations sur la Voiture',
    'profile.personalInfo': 'Informations Personnelles',
    'profile.fullName': 'Nom Complet',
    'profile.email': 'Email',
    'profile.phone': 'Numéro de Téléphone',
    'profile.carMake': 'Marque',
    'profile.carModel': 'Modèle',
    'profile.carYear': 'Année',
    'profile.carPlate': 'Plaque',
    'profile.subscription': 'Abonnement',
    'profile.logout': 'Se Déconnecter',
    
    'dashboard.maintenance': 'État de Maintenance',
    'dashboard.oil': 'Huile',
    'dashboard.gas': 'Essence',
    'dashboard.parking': 'Place de Parking',
    'dashboard.noParking': 'Aucune place enregistrée',
    'dashboard.saveSpot': 'Enregistrer la Place Actuelle',
    'dashboard.spotSaved': 'Place enregistrée!',
    'dashboard.locationMarked': 'Emplacement marqué à votre position actuelle',
    'dashboard.openingNav': 'Ouverture de la navigation...',
    'dashboard.documents': 'Expiration des Documents',
    'dashboard.nextExpire': 'Prochain à expirer',
    'dashboard.daysLeft': 'jours restants',
    'dashboard.insurance': 'Assurance',
    'dashboard.registration': 'Immatriculation',
    'dashboard.inspection': 'Inspection',
    'dashboard.finance': 'Aperçu Financier',
    'dashboard.thisMonth': 'ce mois-ci',
    'dashboard.lessThanLast': 'de moins que le mois dernier',
    'dashboard.maintenance2': 'Maintenance',
    'dashboard.logExpense': 'Enregistrer une Dépense',
    'dashboard.expenseSoon': 'Fonction d\'enregistrement des dépenses bientôt disponible!',
    
    'mileage.title': 'Suivi du Kilométrage',
    'mileage.currentTrip': 'Trajet Actuel',
    'mileage.readyTrack': 'Prêt à Suivre',
    'mileage.startTracking': 'Démarrer le Suivi',
    'mileage.stopSave': 'Arrêter et Enregistrer',
    'mileage.trackingStarted': 'Suivi Démarré',
    'mileage.recording': 'Enregistrement de votre kilométrage...',
    'mileage.tripSaved': 'Trajet Enregistré',
    'mileage.distance': 'Distance',
    'mileage.tripHistory': 'Historique des Trajets',
    'mileage.clear': 'Effacer',
    'mileage.historyCleared': 'Historique Effacé',
    'mileage.dataReset': 'Toutes les données de trajet ont été réinitialisées',
    'mileage.noTrips': 'Aucun trajet enregistré',
    'mileage.totalMileage': 'Kilométrage Total',
    'mileage.trip': 'Trajet',
    'mileage.howWorks': 'Comment ça marche',
    'mileage.usesGPS': 'Le suivi du kilométrage utilise le GPS de votre appareil pour calculer automatiquement la distance parcourue.',
    'mileage.startBefore': 'Démarrez le suivi avant votre trajet et arrêtez quand vous avez terminé. Tous les trajets sont enregistrés dans votre historique.',
    'mileage.requiresLocation': 'Remarque: Nécessite des autorisations de localisation et fonctionne mieux avec une haute précision GPS.',
    'mileage.lat': 'Lat',
    'mileage.lng': 'Lng',
    'mileage.accuracy': 'Précision',
    
    'notifications.title': 'Notifications',
    'notifications.push': 'Notifications Push',
    'notifications.enabled': 'Activé',
    'notifications.disabled': 'Désactivé',
    'notifications.enableReceive': 'Activez les notifications pour recevoir des alertes concernant:',
    'notifications.maintenanceReminders': 'Rappels de maintenance à venir',
    'notifications.expirationWarnings': 'Avertissements d\'expiration de documents',
    'notifications.appointments': 'Confirmations de rendez-vous de service',
    'notifications.updates': 'Mises à jour importantes du véhicule',
    'notifications.deviceToken': 'Jeton de l\'Appareil',
    'notifications.howWorks': 'Comment ça marche',
    'notifications.whenEnabled': 'Lorsque vous activez les notifications push, CarCare peut vous envoyer des alertes en temps opportun même lorsque l\'application est fermée.',
    'notifications.requiresNative': 'Remarque: Les notifications push nécessitent l\'application mobile native (iOS ou Android). Elles ne fonctionnent pas dans le navigateur web.',
    
    'subscription.title': 'Plans d\'Abonnement',
    'subscription.subtitle': 'Choisissez le plan qui vous convient',
    'subscription.currentPlan': 'Plan Actuel',
    'subscription.renewsOn': 'Votre accès premium est renouvelé le',
    'subscription.manageSubscription': 'Gérer l\'Abonnement',
    'subscription.statusRefreshed': 'Statut d\'abonnement actualisé',
    'subscription.checkoutError': 'Échec de création de la session de paiement',
    'subscription.portalError': 'Échec de l\'ouverture du portail client',
    'subscription.generalError': 'Quelque chose s\'est mal passé',
    'subscription.loading': 'Chargement...',
    'subscription.free': 'Gratuit',
    'subscription.premium': 'Premium',
    'subscription.active': 'Actif',
    'subscription.perMonth': '/mois',
    'subscription.upgradeToPremium': 'Passer à Premium',
    'subscription.freeFeature1': 'Suivi de maintenance de base',
    'subscription.freeFeature2': 'Enregistrer 1 place de parking',
    'subscription.freeFeature3': 'Voir l\'expiration des documents à venir',
    'subscription.freeFeature4': 'Suivi des dépenses de base',
    'subscription.premiumFeature1': 'Suivi de maintenance illimité',
    'subscription.premiumFeature2': 'Places de parking illimitées avec carte',
    'subscription.premiumFeature3': 'Alertes d\'expiration de documents',
    'subscription.premiumFeature4': 'Informations financières avancées',
    'subscription.premiumFeature5': 'Support prioritaire',
    'subscription.premiumFeature6': 'Exporter des rapports',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.services': 'Dienstleistungen',
    'nav.profile': 'Profil',
    'nav.notifications': 'Benachrichtigungen',
    
    'header.appTitle': 'CarCare',
    'header.appSubtitle': 'Ihr digitaler Copilot',
    'header.signOutSuccess': 'Erfolgreich abgemeldet',
    
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.back': 'Zurück',
    
    'services.title': 'Servicezentren',
    'services.findNearby': 'Orte in der Nähe Finden',
    'services.enableLocation': 'Standort Aktivieren',
    'services.searchByCategory': 'Nach Kategorie Suchen',
    'services.serviceCenters': 'Servicezentren',
    'services.carWash': 'Autowäsche',
    'services.gasStations': 'Tankstellen',
    'services.getDirections': 'Wegbeschreibung',
    'services.routeTo': 'Route nach',
    'services.foundPlaces': 'Gefundene Orte',
    'services.clickCategory': 'Klicken Sie auf eine Kategorie zum Suchen',
    'services.searching': 'Suchen...',
    'services.kmAway': 'km entfernt',
    
    'profile.title': 'Profil',
    'profile.language': 'Sprache',
    'profile.selectLanguage': 'Sprache Wählen',
    'profile.carInfo': 'Fahrzeuginformationen',
    'profile.personalInfo': 'Persönliche Informationen',
    'profile.fullName': 'Vollständiger Name',
    'profile.email': 'E-Mail',
    'profile.phone': 'Telefonnummer',
    'profile.carMake': 'Automarke',
    'profile.carModel': 'Automodell',
    'profile.carYear': 'Baujahr',
    'profile.carPlate': 'Kennzeichen',
    'profile.subscription': 'Abonnement',
    'profile.logout': 'Abmelden',
    
    'dashboard.maintenance': 'Wartungsstatus',
    'dashboard.oil': 'Öl',
    'dashboard.gas': 'Benzin',
    'dashboard.parking': 'Parkplatz',
    'dashboard.noParking': 'Kein Parkplatz gespeichert',
    'dashboard.saveSpot': 'Aktuellen Platz Speichern',
    'dashboard.spotSaved': 'Parkplatz gespeichert!',
    'dashboard.locationMarked': 'Standort an Ihrer aktuellen Position markiert',
    'dashboard.openingNav': 'Navigation wird geöffnet...',
    'dashboard.documents': 'Dokumentenablauf',
    'dashboard.nextExpire': 'Läuft als nächstes ab',
    'dashboard.daysLeft': 'Tage übrig',
    'dashboard.insurance': 'Versicherung',
    'dashboard.registration': 'Zulassung',
    'dashboard.inspection': 'Inspektion',
    'dashboard.finance': 'Finanzübersicht',
    'dashboard.thisMonth': 'diesen Monat',
    'dashboard.lessThanLast': 'weniger als letzten Monat',
    'dashboard.maintenance2': 'Wartung',
    'dashboard.logExpense': 'Ausgabe Erfassen',
    'dashboard.expenseSoon': 'Ausgabenerfassung bald verfügbar!',
    
    'mileage.title': 'Kilometerzähler',
    'mileage.currentTrip': 'Aktuelle Fahrt',
    'mileage.readyTrack': 'Bereit zur Verfolgung',
    'mileage.startTracking': 'Verfolgung Starten',
    'mileage.stopSave': 'Stoppen & Speichern',
    'mileage.trackingStarted': 'Verfolgung Gestartet',
    'mileage.recording': 'Ihre Kilometerleistung wird aufgezeichnet...',
    'mileage.tripSaved': 'Fahrt Gespeichert',
    'mileage.distance': 'Entfernung',
    'mileage.tripHistory': 'Fahrtenhistorie',
    'mileage.clear': 'Löschen',
    'mileage.historyCleared': 'Historie Gelöscht',
    'mileage.dataReset': 'Alle Fahrtdaten wurden zurückgesetzt',
    'mileage.noTrips': 'Noch keine Fahrten aufgezeichnet',
    'mileage.totalMileage': 'Gesamtkilometer',
    'mileage.trip': 'Fahrt',
    'mileage.howWorks': 'So funktioniert es',
    'mileage.usesGPS': 'Der Kilometerzähler verwendet das GPS Ihres Geräts, um die zurückgelegte Strecke automatisch zu berechnen.',
    'mileage.startBefore': 'Starten Sie die Verfolgung vor Ihrer Fahrt und stoppen Sie, wenn Sie fertig sind. Alle Fahrten werden in Ihrer Historie gespeichert.',
    'mileage.requiresLocation': 'Hinweis: Erfordert Standortberechtigungen und funktioniert am besten mit hoher GPS-Genauigkeit.',
    'mileage.lat': 'Breitengrad',
    'mileage.lng': 'Längengrad',
    'mileage.accuracy': 'Genauigkeit',
    
    'notifications.title': 'Benachrichtigungen',
    'notifications.push': 'Push-Benachrichtigungen',
    'notifications.enabled': 'Aktiviert',
    'notifications.disabled': 'Deaktiviert',
    'notifications.enableReceive': 'Aktivieren Sie Benachrichtigungen, um Warnungen zu erhalten über:',
    'notifications.maintenanceReminders': 'Anstehende Wartungserinnerungen',
    'notifications.expirationWarnings': 'Warnungen zum Dokumentenablauf',
    'notifications.appointments': 'Serviceterminbestätigungen',
    'notifications.updates': 'Wichtige Fahrzeugaktualisierungen',
    'notifications.deviceToken': 'Gerätetoken',
    'notifications.howWorks': 'So funktioniert es',
    'notifications.whenEnabled': 'Wenn Sie Push-Benachrichtigungen aktivieren, kann CarCare Ihnen rechtzeitige Warnungen senden, auch wenn die App geschlossen ist.',
    'notifications.requiresNative': 'Hinweis: Push-Benachrichtigungen erfordern die native mobile App (iOS oder Android). Sie funktionieren nicht im Webbrowser.',
    
    'subscription.title': 'Abonnementpläne',
    'subscription.subtitle': 'Wählen Sie den Plan, der zu Ihnen passt',
    'subscription.currentPlan': 'Aktueller Plan',
    'subscription.renewsOn': 'Ihr Premium-Zugang verlängert sich am',
    'subscription.manageSubscription': 'Abonnement Verwalten',
    'subscription.statusRefreshed': 'Abonnementstatus aktualisiert',
    'subscription.checkoutError': 'Fehler beim Erstellen der Checkout-Sitzung',
    'subscription.portalError': 'Fehler beim Öffnen des Kundenportals',
    'subscription.generalError': 'Etwas ist schief gelaufen',
    'subscription.loading': 'Laden...',
    'subscription.free': 'Kostenlos',
    'subscription.premium': 'Premium',
    'subscription.active': 'Aktiv',
    'subscription.perMonth': '/Monat',
    'subscription.upgradeToPremium': 'Auf Premium upgraden',
    'subscription.freeFeature1': 'Basis Wartungsverfolgung',
    'subscription.freeFeature2': '1 Parkplatz speichern',
    'subscription.freeFeature3': 'Anstehenden Dokumentenablauf anzeigen',
    'subscription.freeFeature4': 'Basis Ausgabenverfolgung',
    'subscription.premiumFeature1': 'Unbegrenzte Wartungsverfolgung',
    'subscription.premiumFeature2': 'Unbegrenzte Parkplätze mit Karte',
    'subscription.premiumFeature3': 'Dokumentenablauf-Warnungen',
    'subscription.premiumFeature4': 'Erweiterte Finanzeinblicke',
    'subscription.premiumFeature5': 'Prioritätssupport',
    'subscription.premiumFeature6': 'Berichte exportieren',
  },
  zh: {
    'nav.home': '主页',
    'nav.services': '服务',
    'nav.profile': '个人资料',
    'nav.notifications': '通知',
    
    'header.appTitle': 'CarCare',
    'header.appSubtitle': '您的数字副驾驶',
    'header.signOutSuccess': '成功退出登录',
    
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.back': '返回',
    
    'services.title': '服务中心',
    'services.findNearby': '查找附近地点',
    'services.enableLocation': '启用位置',
    'services.searchByCategory': '按类别搜索',
    'services.serviceCenters': '服务中心',
    'services.carWash': '洗车',
    'services.gasStations': '加油站',
    'services.getDirections': '获取路线',
    'services.routeTo': '前往',
    'services.foundPlaces': '找到的地点',
    'services.clickCategory': '点击类别进行搜索',
    'services.searching': '搜索中...',
    'services.kmAway': '公里',
    
    'profile.title': '个人资料',
    'profile.language': '语言',
    'profile.selectLanguage': '选择语言',
    'profile.carInfo': '车辆信息',
    'profile.personalInfo': '个人信息',
    'profile.fullName': '全名',
    'profile.email': '电子邮件',
    'profile.phone': '电话号码',
    'profile.carMake': '汽车品牌',
    'profile.carModel': '汽车型号',
    'profile.carYear': '年份',
    'profile.carPlate': '车牌',
    'profile.subscription': '订阅',
    'profile.logout': '退出登录',
    
    'dashboard.maintenance': '维护状态',
    'dashboard.oil': '机油',
    'dashboard.gas': '汽油',
    'dashboard.parking': '停车位',
    'dashboard.noParking': '未保存停车位',
    'dashboard.saveSpot': '保存当前位置',
    'dashboard.spotSaved': '停车位已保存！',
    'dashboard.locationMarked': '位置已标记在当前位置',
    'dashboard.openingNav': '正在打开导航...',
    'dashboard.documents': '文件到期',
    'dashboard.nextExpire': '下一个到期',
    'dashboard.daysLeft': '剩余天数',
    'dashboard.insurance': '保险',
    'dashboard.registration': '注册',
    'dashboard.inspection': '检查',
    'dashboard.finance': '财务概览',
    'dashboard.thisMonth': '本月',
    'dashboard.lessThanLast': '少于上个月',
    'dashboard.maintenance2': '维护',
    'dashboard.logExpense': '记录支出',
    'dashboard.expenseSoon': '支出记录功能即将推出！',
    
    'mileage.title': '里程追踪器',
    'mileage.currentTrip': '当前行程',
    'mileage.readyTrack': '准备追踪',
    'mileage.startTracking': '开始追踪',
    'mileage.stopSave': '停止并保存',
    'mileage.trackingStarted': '追踪已开始',
    'mileage.recording': '正在记录您的里程...',
    'mileage.tripSaved': '行程已保存',
    'mileage.distance': '距离',
    'mileage.tripHistory': '行程历史',
    'mileage.clear': '清除',
    'mileage.historyCleared': '历史已清除',
    'mileage.dataReset': '所有行程数据已重置',
    'mileage.noTrips': '尚未记录行程',
    'mileage.totalMileage': '总里程',
    'mileage.trip': '行程',
    'mileage.howWorks': '如何工作',
    'mileage.usesGPS': '里程追踪器使用设备的GPS自动计算行驶距离。',
    'mileage.startBefore': '在行程开始前启动追踪，完成后停止。所有行程都保存在历史记录中。',
    'mileage.requiresLocation': '注意：需要位置权限，高GPS精度效果最佳。',
    'mileage.lat': '纬度',
    'mileage.lng': '经度',
    'mileage.accuracy': '精度',
    
    'notifications.title': '通知',
    'notifications.push': '推送通知',
    'notifications.enabled': '已启用',
    'notifications.disabled': '已禁用',
    'notifications.enableReceive': '启用通知以接收有关以下内容的提醒：',
    'notifications.maintenanceReminders': '即将到来的维护提醒',
    'notifications.expirationWarnings': '文件到期警告',
    'notifications.appointments': '服务预约确认',
    'notifications.updates': '重要车辆更新',
    'notifications.deviceToken': '设备令牌',
    'notifications.howWorks': '如何工作',
    'notifications.whenEnabled': '启用推送通知后，即使应用关闭,CarCare也可以及时向您发送提醒。',
    'notifications.requiresNative': '注意：推送通知需要原生移动应用（iOS或Android）。在网页浏览器中无法使用。',
    
    'subscription.title': '订阅计划',
    'subscription.subtitle': '选择适合您的计划',
    'subscription.currentPlan': '当前计划',
    'subscription.renewsOn': '您的高级访问权限将于以下日期续订',
    'subscription.manageSubscription': '管理订阅',
    'subscription.statusRefreshed': '订阅状态已刷新',
    'subscription.checkoutError': '创建结账会话失败',
    'subscription.portalError': '打开客户门户失败',
    'subscription.generalError': '出了点问题',
    'subscription.loading': '加载中...',
    'subscription.free': '免费',
    'subscription.premium': '高级',
    'subscription.active': '活跃',
    'subscription.perMonth': '/月',
    'subscription.upgradeToPremium': '升级到高级版',
    'subscription.freeFeature1': '基本维护跟踪',
    'subscription.freeFeature2': '保存1个停车位',
    'subscription.freeFeature3': '查看即将到期的文档',
    'subscription.freeFeature4': '基本费用跟踪',
    'subscription.premiumFeature1': '无限制维护跟踪',
    'subscription.premiumFeature2': '带地图的无限停车位',
    'subscription.premiumFeature3': '文档到期警报',
    'subscription.premiumFeature4': '高级财务洞察',
    'subscription.premiumFeature5': '优先支持',
    'subscription.premiumFeature6': '导出报告',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.services': 'الخدمات',
    'nav.profile': 'الملف الشخصي',
    'nav.notifications': 'الإشعارات',
    
    'header.appTitle': 'CarCare',
    'header.appSubtitle': 'مساعدك الرقمي',
    'header.signOutSuccess': 'تم تسجيل الخروج بنجاح',
    
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجاح',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.back': 'رجوع',
    
    'services.title': 'مراكز الخدمة',
    'services.findNearby': 'العثور على أماكن قريبة',
    'services.enableLocation': 'تفعيل الموقع',
    'services.searchByCategory': 'البحث حسب الفئة',
    'services.serviceCenters': 'مراكز الخدمة',
    'services.carWash': 'غسيل السيارات',
    'services.gasStations': 'محطات الوقود',
    'services.getDirections': 'الحصول على الاتجاهات',
    'services.routeTo': 'الطريق إلى',
    'services.foundPlaces': 'الأماكن الموجودة',
    'services.clickCategory': 'انقر على فئة للبحث',
    'services.searching': 'جاري البحث...',
    'services.kmAway': 'كم',
    
    'profile.title': 'الملف الشخصي',
    'profile.language': 'اللغة',
    'profile.selectLanguage': 'اختر اللغة',
    'profile.carInfo': 'معلومات السيارة',
    'profile.personalInfo': 'المعلومات الشخصية',
    'profile.fullName': 'الاسم الكامل',
    'profile.email': 'البريد الإلكتروني',
    'profile.phone': 'رقم الهاتف',
    'profile.carMake': 'صانع السيارة',
    'profile.carModel': 'طراز السيارة',
    'profile.carYear': 'السنة',
    'profile.carPlate': 'لوحة الترخيص',
    'profile.subscription': 'الاشتراك',
    'profile.logout': 'تسجيل الخروج',
    
    'dashboard.maintenance': 'حالة الصيانة',
    'dashboard.oil': 'الزيت',
    'dashboard.gas': 'الوقود',
    'dashboard.parking': 'موقف السيارات',
    'dashboard.noParking': 'لا يوجد موقف محفوظ',
    'dashboard.saveSpot': 'حفظ الموقع الحالي',
    'dashboard.spotSaved': 'تم حفظ الموقف!',
    'dashboard.locationMarked': 'تم تحديد الموقع في موضعك الحالي',
    'dashboard.openingNav': 'جاري فتح التنقل...',
    'dashboard.documents': 'انتهاء صلاحية المستندات',
    'dashboard.nextExpire': 'التالي للانتهاء',
    'dashboard.daysLeft': 'الأيام المتبقية',
    'dashboard.insurance': 'التأمين',
    'dashboard.registration': 'التسجيل',
    'dashboard.inspection': 'الفحص',
    'dashboard.finance': 'نظرة مالية عامة',
    'dashboard.thisMonth': 'هذا الشهر',
    'dashboard.lessThanLast': 'أقل من الشهر الماضي',
    'dashboard.maintenance2': 'الصيانة',
    'dashboard.logExpense': 'تسجيل النفقات',
    'dashboard.expenseSoon': 'ميزة تسجيل النفقات قريبًا!',
    
    'mileage.title': 'متتبع المسافة المقطوعة',
    'mileage.currentTrip': 'الرحلة الحالية',
    'mileage.readyTrack': 'جاهز للتتبع',
    'mileage.startTracking': 'بدء التتبع',
    'mileage.stopSave': 'إيقاف وحفظ',
    'mileage.trackingStarted': 'بدأ التتبع',
    'mileage.recording': 'جاري تسجيل المسافة المقطوعة...',
    'mileage.tripSaved': 'تم حفظ الرحلة',
    'mileage.distance': 'المسافة',
    'mileage.tripHistory': 'سجل الرحلات',
    'mileage.clear': 'مسح',
    'mileage.historyCleared': 'تم مسح السجل',
    'mileage.dataReset': 'تم إعادة تعيين جميع بيانات الرحلة',
    'mileage.noTrips': 'لم يتم تسجيل أي رحلات بعد',
    'mileage.totalMileage': 'إجمالي المسافة المقطوعة',
    'mileage.trip': 'رحلة',
    'mileage.howWorks': 'كيف يعمل',
    'mileage.usesGPS': 'يستخدم متتبع المسافة المقطوعة نظام تحديد المواقع GPS الخاص بجهازك لحساب المسافة المقطوعة تلقائيًا.',
    'mileage.startBefore': 'ابدأ التتبع قبل رحلتك وأوقف عند الانتهاء. يتم حفظ جميع الرحلات في سجلك.',
    'mileage.requiresLocation': 'ملاحظة: يتطلب أذونات الموقع ويعمل بشكل أفضل مع دقة GPS عالية.',
    'mileage.lat': 'خط العرض',
    'mileage.lng': 'خط الطول',
    'mileage.accuracy': 'الدقة',
    
    'notifications.title': 'الإشعارات',
    'notifications.push': 'الإشعارات الفورية',
    'notifications.enabled': 'مفعل',
    'notifications.disabled': 'معطل',
    'notifications.enableReceive': 'قم بتفعيل الإشعارات لتلقي تنبيهات حول:',
    'notifications.maintenanceReminders': 'تذكيرات الصيانة القادمة',
    'notifications.expirationWarnings': 'تحذيرات انتهاء صلاحية المستندات',
    'notifications.appointments': 'تأكيدات مواعيد الخدمة',
    'notifications.updates': 'تحديثات المركبة المهمة',
    'notifications.deviceToken': 'رمز الجهاز',
    'notifications.howWorks': 'كيف يعمل',
    'notifications.whenEnabled': 'عند تفعيل الإشعارات الفورية، يمكن لـ CarCare إرسال تنبيهات في الوقت المناسب حتى عند إغلاق التطبيق.',
    'notifications.requiresNative': 'ملاحظة: تتطلب الإشعارات الفورية تطبيق الهاتف المحمول الأصلي (iOS أو Android). لن تعمل في متصفح الويب.',
    
    'subscription.title': 'خطط الاشتراك',
    'subscription.subtitle': 'اختر الخطة التي تناسبك',
    'subscription.currentPlan': 'الخطة الحالية',
    'subscription.renewsOn': 'يتجدد وصولك المميز في',
    'subscription.manageSubscription': 'إدارة الاشتراك',
    'subscription.statusRefreshed': 'تم تحديث حالة الاشتراك',
    'subscription.checkoutError': 'فشل إنشاء جلسة الدفع',
    'subscription.portalError': 'فشل فتح بوابة العميل',
    'subscription.generalError': 'حدث خطأ ما',
    'subscription.loading': 'جاري التحميل...',
    'subscription.free': 'مجاني',
    'subscription.premium': 'مميز',
    'subscription.active': 'نشط',
    'subscription.perMonth': '/شهر',
    'subscription.upgradeToPremium': 'الترقية إلى المميز',
    'subscription.freeFeature1': 'تتبع الصيانة الأساسي',
    'subscription.freeFeature2': 'حفظ موقف سيارة واحد',
    'subscription.freeFeature3': 'عرض انتهاء صلاحية المستندات القادمة',
    'subscription.freeFeature4': 'تتبع النفقات الأساسي',
    'subscription.premiumFeature1': 'تتبع صيانة غير محدود',
    'subscription.premiumFeature2': 'مواقف سيارات غير محدودة مع خريطة',
    'subscription.premiumFeature3': 'تنبيهات انتهاء صلاحية المستندات',
    'subscription.premiumFeature4': 'رؤى مالية متقدمة',
    'subscription.premiumFeature5': 'دعم ذو أولوية',
    'subscription.premiumFeature6': 'تصدير التقارير',
  },
  pt: {
    'nav.home': 'Início',
    'nav.services': 'Serviços',
    'nav.profile': 'Perfil',
    'nav.notifications': 'Notificações',
    
    'header.appTitle': 'CarCare',
    'header.appSubtitle': 'Seu copiloto digital',
    'header.signOutSuccess': 'Sessão encerrada com sucesso',
    
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.back': 'Voltar',
    
    'services.title': 'Centros de Serviço',
    'services.findNearby': 'Encontrar Locais Próximos',
    'services.enableLocation': 'Ativar Localização',
    'services.searchByCategory': 'Buscar por Categoria',
    'services.serviceCenters': 'Centros de Serviço',
    'services.carWash': 'Lava-Rápido',
    'services.gasStations': 'Postos de Gasolina',
    'services.getDirections': 'Obter Direções',
    'services.routeTo': 'Rota para',
    'services.foundPlaces': 'Locais Encontrados',
    'services.clickCategory': 'Clique em uma categoria para pesquisar',
    'services.searching': 'Pesquisando...',
    'services.kmAway': 'km de distância',
    
    'profile.title': 'Perfil',
    'profile.language': 'Idioma',
    'profile.selectLanguage': 'Selecionar Idioma',
    'profile.carInfo': 'Informações do Carro',
    'profile.personalInfo': 'Informações Pessoais',
    'profile.fullName': 'Nome Completo',
    'profile.email': 'Email',
    'profile.phone': 'Número de Telefone',
    'profile.carMake': 'Marca do Carro',
    'profile.carModel': 'Modelo do Carro',
    'profile.carYear': 'Ano',
    'profile.carPlate': 'Placa',
    'profile.subscription': 'Assinatura',
    'profile.logout': 'Sair',
    
    'dashboard.maintenance': 'Status de Manutenção',
    'dashboard.oil': 'Óleo',
    'dashboard.gas': 'Gasolina',
    'dashboard.parking': 'Vaga de Estacionamento',
    'dashboard.noParking': 'Nenhuma vaga salva',
    'dashboard.saveSpot': 'Salvar Local Atual',
    'dashboard.spotSaved': 'Vaga salva!',
    'dashboard.locationMarked': 'Localização marcada na sua posição atual',
    'dashboard.openingNav': 'Abrindo navegação...',
    'dashboard.documents': 'Expiração de Documentos',
    'dashboard.nextExpire': 'Próximo a expirar',
    'dashboard.daysLeft': 'dias restantes',
    'dashboard.insurance': 'Seguro',
    'dashboard.registration': 'Registro',
    'dashboard.inspection': 'Inspeção',
    'dashboard.finance': 'Visão Geral Financeira',
    'dashboard.thisMonth': 'este mês',
    'dashboard.lessThanLast': 'menos que o mês passado',
    'dashboard.maintenance2': 'Manutenção',
    'dashboard.logExpense': 'Registrar Despesa',
    'dashboard.expenseSoon': 'Recurso de registro de despesas em breve!',
    
    'mileage.title': 'Rastreador de Quilometragem',
    'mileage.currentTrip': 'Viagem Atual',
    'mileage.readyTrack': 'Pronto para Rastrear',
    'mileage.startTracking': 'Iniciar Rastreamento',
    'mileage.stopSave': 'Parar e Salvar',
    'mileage.trackingStarted': 'Rastreamento Iniciado',
    'mileage.recording': 'Registrando sua quilometragem...',
    'mileage.tripSaved': 'Viagem Salva',
    'mileage.distance': 'Distância',
    'mileage.tripHistory': 'Histórico de Viagens',
    'mileage.clear': 'Limpar',
    'mileage.historyCleared': 'Histórico Limpo',
    'mileage.dataReset': 'Todos os dados da viagem foram redefinidos',
    'mileage.noTrips': 'Nenhuma viagem registrada ainda',
    'mileage.totalMileage': 'Quilometragem Total',
    'mileage.trip': 'Viagem',
    'mileage.howWorks': 'Como funciona',
    'mileage.usesGPS': 'O rastreador de quilometragem usa o GPS do seu dispositivo para calcular automaticamente a distância percorrida.',
    'mileage.startBefore': 'Inicie o rastreamento antes da sua viagem e pare quando terminar. Todas as viagens são salvas no seu histórico.',
    'mileage.requiresLocation': 'Nota: Requer permissões de localização e funciona melhor com alta precisão de GPS.',
    'mileage.lat': 'Lat',
    'mileage.lng': 'Long',
    'mileage.accuracy': 'Precisão',
    
    'notifications.title': 'Notificações',
    'notifications.push': 'Notificações Push',
    'notifications.enabled': 'Ativado',
    'notifications.disabled': 'Desativado',
    'notifications.enableReceive': 'Ative as notificações para receber alertas sobre:',
    'notifications.maintenanceReminders': 'Lembretes de manutenção futura',
    'notifications.expirationWarnings': 'Avisos de expiração de documentos',
    'notifications.appointments': 'Confirmações de compromissos de serviço',
    'notifications.updates': 'Atualizações importantes do veículo',
    'notifications.deviceToken': 'Token do Dispositivo',
    'notifications.howWorks': 'Como funciona',
    'notifications.whenEnabled': 'Quando você ativa as notificações push, o CarCare pode enviar alertas oportunos mesmo quando o aplicativo está fechado.',
    'notifications.requiresNative': 'Nota: As notificações push exigem o aplicativo móvel nativo (iOS ou Android). Elas não funcionam no navegador web.',
    
    'subscription.title': 'Planos de Assinatura',
    'subscription.subtitle': 'Escolha o plano que funciona para você',
    'subscription.currentPlan': 'Plano Atual',
    'subscription.renewsOn': 'Seu acesso premium renova em',
    'subscription.manageSubscription': 'Gerenciar Assinatura',
    'subscription.statusRefreshed': 'Status da assinatura atualizado',
    'subscription.checkoutError': 'Falha ao criar sessão de checkout',
    'subscription.portalError': 'Falha ao abrir portal do cliente',
    'subscription.generalError': 'Algo deu errado',
    'subscription.loading': 'Carregando...',
    'subscription.free': 'Grátis',
    'subscription.premium': 'Premium',
    'subscription.active': 'Ativo',
    'subscription.perMonth': '/mês',
    'subscription.upgradeToPremium': 'Atualizar para Premium',
    'subscription.freeFeature1': 'Rastreamento básico de manutenção',
    'subscription.freeFeature2': 'Salvar 1 vaga de estacionamento',
    'subscription.freeFeature3': 'Ver expiração de documentos futuros',
    'subscription.freeFeature4': 'Rastreamento básico de despesas',
    'subscription.premiumFeature1': 'Rastreamento ilimitado de manutenção',
    'subscription.premiumFeature2': 'Vagas de estacionamento ilimitadas com mapa',
    'subscription.premiumFeature3': 'Alertas de expiração de documentos',
    'subscription.premiumFeature4': 'Insights financeiros avançados',
    'subscription.premiumFeature5': 'Suporte prioritário',
    'subscription.premiumFeature6': 'Exportar relatórios',
  },
  ru: {
    'nav.home': 'Главная',
    'nav.services': 'Услуги',
    'nav.profile': 'Профиль',
    'nav.notifications': 'Уведомления',
    
    'header.appTitle': 'CarCare',
    'header.appSubtitle': 'Ваш цифровой помощник',
    'header.signOutSuccess': 'Успешный выход',
    
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.success': 'Успешно',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.back': 'Назад',
    
    'services.title': 'Сервисные Центры',
    'services.findNearby': 'Найти Ближайшие Места',
    'services.enableLocation': 'Включить Местоположение',
    'services.searchByCategory': 'Поиск по Категории',
    'services.serviceCenters': 'Сервисные Центры',
    'services.carWash': 'Автомойка',
    'services.gasStations': 'АЗС',
    'services.getDirections': 'Показать Маршрут',
    'services.routeTo': 'Маршрут к',
    'services.foundPlaces': 'Найдено Мест',
    'services.clickCategory': 'Нажмите на категорию для поиска',
    'services.searching': 'Поиск...',
    'services.kmAway': 'км',
    
    'profile.title': 'Профиль',
    'profile.language': 'Язык',
    'profile.selectLanguage': 'Выбрать Язык',
    'profile.carInfo': 'Информация об Автомобиле',
    'profile.personalInfo': 'Личная Информация',
    'profile.fullName': 'Полное Имя',
    'profile.email': 'Email',
    'profile.phone': 'Номер Телефона',
    'profile.carMake': 'Марка',
    'profile.carModel': 'Модель',
    'profile.carYear': 'Год',
    'profile.carPlate': 'Номер',
    'profile.subscription': 'Подписка',
    'profile.logout': 'Выйти',
    
    'dashboard.maintenance': 'Статус Обслуживания',
    'dashboard.oil': 'Масло',
    'dashboard.gas': 'Бензин',
    'dashboard.parking': 'Место Парковки',
    'dashboard.noParking': 'Место не сохранено',
    'dashboard.saveSpot': 'Сохранить Текущее Место',
    'dashboard.spotSaved': 'Место сохранено!',
    'dashboard.locationMarked': 'Местоположение отмечено на вашей текущей позиции',
    'dashboard.openingNav': 'Открытие навигации...',
    'dashboard.documents': 'Срок Действия Документов',
    'dashboard.nextExpire': 'Следующий истекает',
    'dashboard.daysLeft': 'дней осталось',
    'dashboard.insurance': 'Страховка',
    'dashboard.registration': 'Регистрация',
    'dashboard.inspection': 'Техосмотр',
    'dashboard.finance': 'Финансовый Обзор',
    'dashboard.thisMonth': 'в этом месяце',
    'dashboard.lessThanLast': 'меньше, чем в прошлом месяце',
    'dashboard.maintenance2': 'Обслуживание',
    'dashboard.logExpense': 'Записать Расход',
    'dashboard.expenseSoon': 'Функция записи расходов скоро!',
    
    'mileage.title': 'Трекер Пробега',
    'mileage.currentTrip': 'Текущая Поездка',
    'mileage.readyTrack': 'Готов к Отслеживанию',
    'mileage.startTracking': 'Начать Отслеживание',
    'mileage.stopSave': 'Остановить и Сохранить',
    'mileage.trackingStarted': 'Отслеживание Начато',
    'mileage.recording': 'Запись вашего пробега...',
    'mileage.tripSaved': 'Поездка Сохранена',
    'mileage.distance': 'Расстояние',
    'mileage.tripHistory': 'История Поездок',
    'mileage.clear': 'Очистить',
    'mileage.historyCleared': 'История Очищена',
    'mileage.dataReset': 'Все данные о поездках были сброшены',
    'mileage.noTrips': 'Поездки еще не записаны',
    'mileage.totalMileage': 'Общий Пробег',
    'mileage.trip': 'Поездка',
    'mileage.howWorks': 'Как это работает',
    'mileage.usesGPS': 'Трекер пробега использует GPS вашего устройства для автоматического расчета пройденного расстояния.',
    'mileage.startBefore': 'Начните отслеживание перед поездкой и остановите по завершении. Все поездки сохраняются в вашей истории.',
    'mileage.requiresLocation': 'Примечание: Требуются разрешения на определение местоположения, лучше всего работает с высокой точностью GPS.',
    'mileage.lat': 'Шир',
    'mileage.lng': 'Долг',
    'mileage.accuracy': 'Точность',
    
    'notifications.title': 'Уведомления',
    'notifications.push': 'Push-Уведомления',
    'notifications.enabled': 'Включено',
    'notifications.disabled': 'Отключено',
    'notifications.enableReceive': 'Включите уведомления, чтобы получать оповещения о:',
    'notifications.maintenanceReminders': 'Предстоящие напоминания о обслуживании',
    'notifications.expirationWarnings': 'Предупреждения об истечении срока действия документов',
    'notifications.appointments': 'Подтверждения сервисных встреч',
    'notifications.updates': 'Важные обновления автомобиля',
    'notifications.deviceToken': 'Токен Устройства',
    'notifications.howWorks': 'Как это работает',
    'notifications.whenEnabled': 'Когда вы включаете push-уведомления, CarCare может отправлять вам своевременные оповещения даже при закрытом приложении.',
    'notifications.requiresNative': 'Примечание: Push-уведомления требуют нативного мобильного приложения (iOS или Android). Они не работают в веб-браузере.',
    
    'subscription.title': 'Планы Подписки',
    'subscription.subtitle': 'Выберите план, который вам подходит',
    'subscription.currentPlan': 'Текущий План',
    'subscription.renewsOn': 'Ваш премиум-доступ продлевается',
    'subscription.manageSubscription': 'Управление Подпиской',
    'subscription.statusRefreshed': 'Статус подписки обновлен',
    'subscription.checkoutError': 'Ошибка создания сеанса оплаты',
    'subscription.portalError': 'Ошибка открытия клиентского портала',
    'subscription.generalError': 'Что-то пошло не так',
    'subscription.loading': 'Загрузка...',
    'subscription.free': 'Бесплатно',
    'subscription.premium': 'Премиум',
    'subscription.active': 'Активен',
    'subscription.perMonth': '/месяц',
    'subscription.upgradeToPremium': 'Перейти на Премиум',
    'subscription.freeFeature1': 'Базовое отслеживание обслуживания',
    'subscription.freeFeature2': 'Сохранить 1 парковочное место',
    'subscription.freeFeature3': 'Просмотр предстоящего истечения документов',
    'subscription.freeFeature4': 'Базовое отслеживание расходов',
    'subscription.premiumFeature1': 'Неограниченное отслеживание обслуживания',
    'subscription.premiumFeature2': 'Неограниченные парковочные места с картой',
    'subscription.premiumFeature3': 'Оповещения об истечении документов',
    'subscription.premiumFeature4': 'Расширенная финансовая аналитика',
    'subscription.premiumFeature5': 'Приоритетная поддержка',
    'subscription.premiumFeature6': 'Экспорт отчетов',
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.services': 'サービス',
    'nav.profile': 'プロフィール',
    'nav.notifications': '通知',
    
    'header.appTitle': 'CarCare',
    'header.appSubtitle': 'あなたのデジタル副操縦士',
    'header.signOutSuccess': 'サインアウトしました',
    
    'common.loading': '読み込み中...',
    'common.error': 'エラー',
    'common.success': '成功',
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.delete': '削除',
    'common.edit': '編集',
    'common.back': '戻る',
    
    'services.title': 'サービスセンター',
    'services.findNearby': '近くの場所を探す',
    'services.enableLocation': '位置情報を有効にする',
    'services.searchByCategory': 'カテゴリーで検索',
    'services.serviceCenters': 'サービスセンター',
    'services.carWash': '洗車',
    'services.gasStations': 'ガソリンスタンド',
    'services.getDirections': 'ルートを取得',
    'services.routeTo': 'までのルート',
    'services.foundPlaces': '見つかった場所',
    'services.clickCategory': 'カテゴリーをクリックして検索',
    'services.searching': '検索中...',
    'services.kmAway': 'km',
    
    'profile.title': 'プロフィール',
    'profile.language': '言語',
    'profile.selectLanguage': '言語を選択',
    'profile.carInfo': '車両情報',
    'profile.personalInfo': '個人情報',
    'profile.fullName': '氏名',
    'profile.email': 'メール',
    'profile.phone': '電話番号',
    'profile.carMake': 'メーカー',
    'profile.carModel': 'モデル',
    'profile.carYear': '年式',
    'profile.carPlate': 'ナンバープレート',
    'profile.subscription': 'サブスクリプション',
    'profile.logout': 'ログアウト',
    
    'dashboard.maintenance': 'メンテナンス状況',
    'dashboard.oil': 'オイル',
    'dashboard.gas': 'ガソリン',
    'dashboard.parking': '駐車場所',
    'dashboard.noParking': '保存された駐車場所なし',
    'dashboard.saveSpot': '現在地を保存',
    'dashboard.spotSaved': '駐車場所を保存しました！',
    'dashboard.locationMarked': '現在地に位置をマークしました',
    'dashboard.openingNav': 'ナビゲーションを開いています...',
    'dashboard.documents': '書類の有効期限',
    'dashboard.nextExpire': '次に期限切れ',
    'dashboard.daysLeft': '残り日数',
    'dashboard.insurance': '保険',
    'dashboard.registration': '登録',
    'dashboard.inspection': '点検',
    'dashboard.finance': '財務概要',
    'dashboard.thisMonth': '今月',
    'dashboard.lessThanLast': '先月より少ない',
    'dashboard.maintenance2': 'メンテナンス',
    'dashboard.logExpense': '支出を記録',
    'dashboard.expenseSoon': '支出記録機能は近日公開！',
    
    'mileage.title': '走行距離トラッカー',
    'mileage.currentTrip': '現在のトリップ',
    'mileage.readyTrack': '追跡準備完了',
    'mileage.startTracking': '追跡を開始',
    'mileage.stopSave': '停止して保存',
    'mileage.trackingStarted': '追跡を開始しました',
    'mileage.recording': '走行距離を記録中...',
    'mileage.tripSaved': 'トリップを保存しました',
    'mileage.distance': '距離',
    'mileage.tripHistory': 'トリップ履歴',
    'mileage.clear': 'クリア',
    'mileage.historyCleared': '履歴をクリアしました',
    'mileage.dataReset': 'すべてのトリップデータがリセットされました',
    'mileage.noTrips': 'まだトリップが記録されていません',
    'mileage.totalMileage': '総走行距離',
    'mileage.trip': 'トリップ',
    'mileage.howWorks': '仕組み',
    'mileage.usesGPS': '走行距離トラッカーは、デバイスのGPSを使用して走行距離を自動的に計算します。',
    'mileage.startBefore': 'トリップ前に追跡を開始し、完了したら停止します。すべてのトリップは履歴に保存されます。',
    'mileage.requiresLocation': '注意：位置情報の許可が必要で、高いGPS精度で最適に動作します。',
    'mileage.lat': '緯度',
    'mileage.lng': '経度',
    'mileage.accuracy': '精度',
    
    'notifications.title': '通知',
    'notifications.push': 'プッシュ通知',
    'notifications.enabled': '有効',
    'notifications.disabled': '無効',
    'notifications.enableReceive': '通知を有効にして、次の項目に関するアラートを受信します：',
    'notifications.maintenanceReminders': '今後のメンテナンスリマインダー',
    'notifications.expirationWarnings': '書類の有効期限警告',
    'notifications.appointments': 'サービス予約の確認',
    'notifications.updates': '重要な車両の更新',
    'notifications.deviceToken': 'デバイストークン',
    'notifications.howWorks': '仕組み',
    'notifications.whenEnabled': 'プッシュ通知を有効にすると、アプリを閉じていてもCarCareがタイムリーなアラートを送信できます。',
    'notifications.requiresNative': '注意：プッシュ通知にはネイティブモバイルアプリ（iOSまたはAndroid）が必要です。Webブラウザでは機能しません。',
    
    'subscription.title': 'サブスクリプションプラン',
    'subscription.subtitle': 'あなたに合ったプランを選択',
    'subscription.currentPlan': '現在のプラン',
    'subscription.renewsOn': 'プレミアムアクセスは次の日に更新されます',
    'subscription.manageSubscription': 'サブスクリプション管理',
    'subscription.statusRefreshed': 'サブスクリプションステータスが更新されました',
    'subscription.checkoutError': 'チェックアウトセッションの作成に失敗しました',
    'subscription.portalError': 'カスタマーポータルを開けませんでした',
    'subscription.generalError': '問題が発生しました',
    'subscription.loading': '読み込み中...',
    'subscription.free': '無料',
    'subscription.premium': 'プレミアム',
    'subscription.active': 'アクティブ',
    'subscription.perMonth': '/月',
    'subscription.upgradeToPremium': 'プレミアムにアップグレード',
    'subscription.freeFeature1': '基本メンテナンス追跡',
    'subscription.freeFeature2': '駐車スポットを1つ保存',
    'subscription.freeFeature3': '今後の書類の有効期限を表示',
    'subscription.freeFeature4': '基本経費追跡',
    'subscription.premiumFeature1': '無制限のメンテナンス追跡',
    'subscription.premiumFeature2': 'マップ付き無制限の駐車スポット',
    'subscription.premiumFeature3': '書類の有効期限アラート',
    'subscription.premiumFeature4': '高度な財務インサイト',
    'subscription.premiumFeature5': '優先サポート',
    'subscription.premiumFeature6': 'レポートのエクスポート',
  },
  hi: {
    'nav.home': 'होम',
    'nav.services': 'सेवाएं',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.notifications': 'सूचनाएं',
    
    'header.appTitle': 'CarCare',
    'header.appSubtitle': 'आपका डिजिटल सह-पायलट',
    'header.signOutSuccess': 'सफलतापूर्वक साइन आउट हो गए',
    
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.back': 'वापस',
    
    'services.title': 'सर्विस सेंटर',
    'services.findNearby': 'आस-पास के स्थान खोजें',
    'services.enableLocation': 'स्थान सक्षम करें',
    'services.searchByCategory': 'श्रेणी द्वारा खोजें',
    'services.serviceCenters': 'सर्विस सेंटर',
    'services.carWash': 'कार वॉश',
    'services.gasStations': 'पेट्रोल पंप',
    'services.getDirections': 'दिशा-निर्देश प्राप्त करें',
    'services.routeTo': 'के लिए मार्ग',
    'services.foundPlaces': 'मिले स्थान',
    'services.clickCategory': 'खोजने के लिए एक श्रेणी पर क्लिक करें',
    'services.searching': 'खोज रहे हैं...',
    'services.kmAway': 'किमी',
    
    'profile.title': 'प्रोफ़ाइल',
    'profile.language': 'भाषा',
    'profile.selectLanguage': 'भाषा चुनें',
    'profile.carInfo': 'कार की जानकारी',
    'profile.personalInfo': 'व्यक्तिगत जानकारी',
    'profile.fullName': 'पूरा नाम',
    'profile.email': 'ईमेल',
    'profile.phone': 'फोन नंबर',
    'profile.carMake': 'कार ब्रांड',
    'profile.carModel': 'कार मॉडल',
    'profile.carYear': 'वर्ष',
    'profile.carPlate': 'लाइसेंस प्लेट',
    'profile.subscription': 'सदस्यता',
    'profile.logout': 'लॉगआउट',
    
    'dashboard.maintenance': 'रखरखाव स्थिति',
    'dashboard.oil': 'तेल',
    'dashboard.gas': 'पेट्रोल',
    'dashboard.parking': 'पार्किंग स्थान',
    'dashboard.noParking': 'कोई पार्किंग स्थान सहेजा नहीं गया',
    'dashboard.saveSpot': 'वर्तमान स्थान सहेजें',
    'dashboard.spotSaved': 'पार्किंग स्थान सहेजा गया!',
    'dashboard.locationMarked': 'आपकी वर्तमान स्थिति पर स्थान चिह्नित किया गया',
    'dashboard.openingNav': 'नेविगेशन खोल रहे हैं...',
    'dashboard.documents': 'दस्तावेज़ समाप्ति',
    'dashboard.nextExpire': 'अगला समाप्त होने वाला',
    'dashboard.daysLeft': 'दिन शेष',
    'dashboard.insurance': 'बीमा',
    'dashboard.registration': 'पंजीकरण',
    'dashboard.inspection': 'निरीक्षण',
    'dashboard.finance': 'वित्तीय अवलोकन',
    'dashboard.thisMonth': 'इस महीने',
    'dashboard.lessThanLast': 'पिछले महीने से कम',
    'dashboard.maintenance2': 'रखरखाव',
    'dashboard.logExpense': 'खर्च दर्ज करें',
    'dashboard.expenseSoon': 'खर्च दर्ज करने की सुविधा जल्द आ रही है!',
    
    'mileage.title': 'माइलेज ट्रैकर',
    'mileage.currentTrip': 'वर्तमान यात्रा',
    'mileage.readyTrack': 'ट्रैक करने के लिए तैयार',
    'mileage.startTracking': 'ट्रैकिंग शुरू करें',
    'mileage.stopSave': 'रोकें और सहेजें',
    'mileage.trackingStarted': 'ट्रैकिंग शुरू हो गई',
    'mileage.recording': 'आपकी माइलेज रिकॉर्ड कर रहे हैं...',
    'mileage.tripSaved': 'यात्रा सहेजी गई',
    'mileage.distance': 'दूरी',
    'mileage.tripHistory': 'यात्रा इतिहास',
    'mileage.clear': 'साफ करें',
    'mileage.historyCleared': 'इतिहास साफ कर दिया गया',
    'mileage.dataReset': 'सभी यात्रा डेटा रीसेट कर दिया गया है',
    'mileage.noTrips': 'अभी तक कोई यात्रा दर्ज नहीं की गई',
    'mileage.totalMileage': 'कुल माइलेज',
    'mileage.trip': 'यात्रा',
    'mileage.howWorks': 'यह कैसे काम करता है',
    'mileage.usesGPS': 'माइलेज ट्रैकर स्वचालित रूप से तय की गई दूरी की गणना करने के लिए आपके उपकरण के GPS का उपयोग करता है।',
    'mileage.startBefore': 'अपनी यात्रा से पहले ट्रैकिंग शुरू करें और समाप्त होने पर रोकें। सभी यात्राएं आपके इतिहास में सहेजी जाती हैं।',
    'mileage.requiresLocation': 'नोट: स्थान अनुमतियों की आवश्यकता है और उच्च GPS सटीकता के साथ सबसे अच्छा काम करता है।',
    'mileage.lat': 'अक्षांश',
    'mileage.lng': 'देशांतर',
    'mileage.accuracy': 'सटीकता',
    
    'notifications.title': 'सूचनाएं',
    'notifications.push': 'पुश नोटिफिकेशन',
    'notifications.enabled': 'सक्षम',
    'notifications.disabled': 'अक्षम',
    'notifications.enableReceive': 'निम्नलिखित के बारे में अलर्ट प्राप्त करने के लिए सूचनाएं सक्षम करें:',
    'notifications.maintenanceReminders': 'आगामी रखरखाव अनुस्मारक',
    'notifications.expirationWarnings': 'दस्तावेज़ समाप्ति चेतावनी',
    'notifications.appointments': 'सेवा नियुक्ति की पुष्टि',
    'notifications.updates': 'महत्वपूर्ण वाहन अपडेट',
    'notifications.deviceToken': 'डिवाइस टोकन',
    'notifications.howWorks': 'यह कैसे काम करता है',
    'notifications.whenEnabled': 'जब आप पुश नोटिफिकेशन सक्षम करते हैं, तो ऐप बंद होने पर भी CarCare आपको समय पर अलर्ट भेज सकता है।',
    'notifications.requiresNative': 'नोट: पुश नोटिफिकेशन के लिए नेटिव मोबाइल ऐप (iOS या Android) की आवश्यकता है। वे वेब ब्राउज़र में काम नहीं करेंगे।',
    
    'subscription.title': 'सब्सक्रिप्शन प्लान',
    'subscription.subtitle': 'अपने लिए उपयुक्त योजना चुनें',
    'subscription.currentPlan': 'वर्तमान योजना',
    'subscription.renewsOn': 'आपकी प्रीमियम पहुंच नवीनीकृत होती है',
    'subscription.manageSubscription': 'सब्सक्रिप्शन प्रबंधित करें',
    'subscription.statusRefreshed': 'सब्सक्रिप्शन स्थिति अपडेट की गई',
    'subscription.checkoutError': 'चेकआउट सत्र बनाने में विफल',
    'subscription.portalError': 'ग्राहक पोर्टल खोलने में विफल',
    'subscription.generalError': 'कुछ गलत हो गया',
    'subscription.loading': 'लोड हो रहा है...',
    'subscription.free': 'मुक्त',
    'subscription.premium': 'प्रीमियम',
    'subscription.active': 'सक्रिय',
    'subscription.perMonth': '/महीना',
    'subscription.upgradeToPremium': 'प्रीमियम में अपग्रेड करें',
    'subscription.freeFeature1': 'बुनियादी रखरखाव ट्रैकिंग',
    'subscription.freeFeature2': '1 पार्किंग स्पॉट सेव करें',
    'subscription.freeFeature3': 'आगामी दस्तावेज़ समाप्ति देखें',
    'subscription.freeFeature4': 'बुनियादी व्यय ट्रैकिंग',
    'subscription.premiumFeature1': 'असीमित रखरखाव ट्रैकिंग',
    'subscription.premiumFeature2': 'मानचित्र के साथ असीमित पार्किंग स्पॉट',
    'subscription.premiumFeature3': 'दस्तावेज़ समाप्ति अलर्ट',
    'subscription.premiumFeature4': 'उन्नत वित्तीय जानकारी',
    'subscription.premiumFeature5': 'प्राथमिकता समर्थन',
    'subscription.premiumFeature6': 'रिपोर्ट निर्यात करें',
  },
};

export const languageNames: Record<Language, string> = {
  en: 'English',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  zh: '中文',
  ar: 'العربية',
  pt: 'Português',
  ru: 'Русский',
  ja: '日本語',
  hi: 'हिन्दी',
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    // Load language from user profile
    const loadLanguage = async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (user) {
        const { data: profile } = await supabase
          .from('profiles')
          .select('language')
          .eq('user_id', user.id)
          .single();
        
        if (profile?.language) {
          setLanguageState(profile.language as Language);
        }
      }
    };

    loadLanguage();
  }, []);

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    
    // Save to user profile
    const { data: { user } } = await supabase.auth.getUser();
    if (user) {
      await supabase
        .from('profiles')
        .update({ language: lang })
        .eq('user_id', user.id);
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
